// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6_mlabar26.Models;

namespace mission6_mlabar26.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230214031043_movie")]
    partial class movie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6_mlabar26.Models.movieForm", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("movieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            category = "Action/Adventure",
                            director = "Christopher Nolan",
                            edited = false,
                            notes = "Great acting, great story!",
                            rating = "PG-13",
                            title = "The Dark Knight",
                            year = "2008"
                        },
                        new
                        {
                            movieID = 2,
                            category = "Comedy",
                            director = "Christopher Nolan",
                            edited = false,
                            rating = "PG-13",
                            title = "Hot Rod",
                            year = "2007"
                        },
                        new
                        {
                            movieID = 3,
                            category = "Action/Adventure",
                            director = "Akiva Schaffer",
                            edited = false,
                            notes = "Love the soundtrack!",
                            rating = "PG-13",
                            title = "Interstellar",
                            year = "2014"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
